In [1]:
'''
Algebra Linear com NumPy
O que iremos desenvolver?

- Definindo  matrizes
- Operações matemáticas
- Matriz transporta
- Determinante
- Matriz inversa
- Sistema Lineares
- Traço e ponto de uma matriz
-  Autovalor / Autovetor
'''
import numpy as np

In [2]:
'''
Definindo Matrizes - Exercício 1
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().

    | 1  2  3 |        | 1  -2  0 |       | 1  2  3 |      | 1 |
A = | 2  1 -1 |    B = | 3   0  1 |   C = | 4  5  6 |  D = | 4 |
                       | 4   5  6 |       | 7  8  9 |      |-3 |
Lembrete: podemos observar que as matrizes B e C são matrizes quadradas, pois o número de linhas é igual ao número de colunas.
'''

'\nDefinindo Matrizes - Exercício 1\nDefina as matrizes abaixo utilizando o NumPy. Use o método np.array().\n\n    | 1  2  3 |        | 1  -2  0 |       | 1  2  3 |      | 1 |\nA = | 2  1 -1 |    B = | 3   0  1 |   C = | 4  5  6 |  D = | 4 |\n                       | 4   5  6 |       | 7  8  9 |      |-3 |\nLembrete: podemos observar que as matrizes B e C são matrizes quadradas, pois o número de linhas é igual ao número de colunas.\n'

In [3]:
A = np.array([[1,2,3],[2,1,-1]])
B = np.array([[1,-2,0],[3,0,1],[4,5,6]])
C = np.array(range(1,10)).reshape(3,3)
D = np.array([[1],[4],[-3]])
print(A)
print()
print(B)
print()
print(C)
print()
print(D)
print()


[[ 1  2  3]
 [ 2  1 -1]]

[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1]
 [ 4]
 [-3]]



In [4]:
'''
Definindo Matrizes - Exercício 2
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().
    | 1 |
    | 2 |
E = | 3 |     F = [1 0 3 -10]
    | 4 |     G = [1 2 3 4 5]
    | 5 |
    | 6 |
'''

'\nDefinindo Matrizes - Exercício 2\nDefina as matrizes abaixo utilizando o NumPy. Use o método np.array().\n    | 1 |\n    | 2 |\nE = | 3 |     F = [1 0 3 -10]\n    | 4 |     G = [1 2 3 4 5]\n    | 5 |\n    | 6 |\n'

In [5]:
E = np.array(range(1,7)).reshape(6,1)
F = np.array([1, 0, 3, -10])
G = np.array(range(1,6))

print(E)
print()
print(F)
print()
print(G)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[  1   0   3 -10]

[1 2 3 4 5]


In [6]:
'''
Definindo Matrizes - Exercício 3
Defina as matrizes abaixo utilizando o NumPy. Use o método np.array().

A = 2 colunas e 2 linhas com 0
B = 5 colunas e 3 linhas com 0
C = 5 colunas e 5 linhas com 0
I1 = 2 colunas e 2 linhas com 1 na diagonal principal
I2 = 3 colunas e 3 linhas com 1 na diagonal principal
I3 = 6 colunas e 6 linhas com 1 na diagonal principal
'''

'\nDefinindo Matrizes - Exercício 3\nDefina as matrizes abaixo utilizando o NumPy. Use o método np.array().\n\nA = 2 colunas e 2 linhas com 0\nB = 5 colunas e 3 linhas com 0\nC = 5 colunas e 5 linhas com 0\nI1 = 2 colunas e 2 linhas com 1 na diagonal principal\nI2 = 3 colunas e 3 linhas com 1 na diagonal principal\nI3 = 6 colunas e 6 linhas com 1 na diagonal principal\n'

In [7]:
A = np.zeros(shape=(2, 2))
B = np.zeros(shape=(3, 5))
C = np.zeros(shape=(5, 5))
I2 = np.eye(2, 2)
I3 = np.eye(3, 3)
I6 = np.eye(6, 6)

print(A)
print()
print(B)
print()
print(C)
print()
print(I2)
print()
print(I3)
print()
print(I6)

[[0. 0.]
 [0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [8]:
'''
Definindo Matrizes - Exercício 4
Defina a matrizes triangulares abaixo utilizando o NumPy. Use os métodos np.triu() e np.tril().

    | 1  2  3 |           | 1  0  0 |           | 100  101  102  103  104 |
A = | 0  5  6 |       B = | 4  5  0 |       C = | 0    106  107  108  109 |
    | 0  0  9 |           | 7  8  9 |           | 0     0   112  113  114 |
                                                | 0     0   0    118  119 |
                                                | 0     0   0     0   124 |

Para informações acesse a documentação:

https://numpy.org/doc/stable/reference/generated/numpy.tril.html

https://numpy.org/doc/stable/reference/generated/numpy.triu.html
'''

'\nDefinindo Matrizes - Exercício 4\nDefina a matrizes triangulares abaixo utilizando o NumPy. Use os métodos np.triu() e np.tril().\n\n    | 1  2  3 |           | 1  0  0 |           | 100  101  102  103  104 |\nA = | 0  5  6 |       B = | 4  5  0 |       C = | 0    106  107  108  109 |\n    | 0  0  9 |           | 7  8  9 |           | 0     0   112  113  114 |\n                                                | 0     0   0    118  119 |\n                                                | 0     0   0     0   124 |\n\nPara informações acesse a documentação:\n\nhttps://numpy.org/doc/stable/reference/generated/numpy.tril.html\n\nhttps://numpy.org/doc/stable/reference/generated/numpy.triu.html\n'

In [9]:
A = np.triu(np.arange(1,10).reshape(3,3), k=0)
B = np.tril(np.arange(1,10).reshape(3,3), k=0)
C = np.triu(np.arange(100,125).reshape(5,5))
print(A)
print()
print(B)
print()
print(C)

[[1 2 3]
 [0 5 6]
 [0 0 9]]

[[1 0 0]
 [4 5 0]
 [7 8 9]]

[[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]


In [10]:
'''
Definindo Matrizes - Exercício 5
Defina as matrizes abaixo utilizando o NumPy. Use os métodos np.diag() e np.array().

    | 7  0  0 |           | 3  0  0  0 |           | -5    0    0    0    0 |
A = | 0  1  0 |       B = | 0  3  0  0 |       C = | 0    -4    0     0   0 |
    | 0  0 -1 |           | 0  0  3  0 |           | 0     0   -3    0    0 |
                          | 0  0  0  3 |           | 0     0   0    -2    0 |
                                                   | 0     0   0     0   -1 |
'''

'\nDefinindo Matrizes - Exercício 5\nDefina as matrizes abaixo utilizando o NumPy. Use os métodos np.diag() e np.array().\n\n    | 7  0  0 |           | 3  0  0  0 |           | -5    0    0    0    0 |\nA = | 0  1  0 |       B = | 0  3  0  0 |       C = | 0    -4    0     0   0 |\n    | 0  0 -1 |           | 0  0  3  0 |           | 0     0   -3    0    0 |\n                          | 0  0  0  3 |           | 0     0   0    -2    0 |\n                                                   | 0     0   0     0   -1 |\n'

In [11]:
A = np.diag([7, 1, -1])
B = np.diag([3]*4)
C = np.diag(range(-5,0))

print(A)
print()
print(B)
print()
print(C)

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]]

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]

[[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]


In [12]:
'''
Operações matriciais - Exercício 1
Defina as matrizes A e B dadas a seguir e obtenha A+B.

    | 10  11 |       | 1  25 |
A = |  5  1  |   B = | 3   4 |
    | -2  4  |       | 0 -10 |
'''

'\nOperações matriciais - Exercício 1\nDefina as matrizes A e B dadas a seguir e obtenha A+B.\n\n    | 10  11 |       | 1  25 |\nA = |  5  1  |   B = | 3   4 |\n    | -2  4  |       | 0 -10 |\n'

In [13]:
A = np.array([[10, 11], [5, 1], [-2, 4]])
B = np.array([[1, 25], [3, 4], [0, -10]])
soma = A + B
print(soma)

[[11 36]
 [ 8  5]
 [-2 -6]]


In [14]:
'''
Operações matriciais - Exercício 2
Para as matrizes a seguir,

    | 10  11 |       | 1  25 |       | 7  3 |
A = |  5  1  |   B = | 3   4 |   C = | 6  1 |
    | -2  4  |       | 0 -10 |       | 0  0 |

Verifique as propriedades da Adição de Matrizes:

A + B = B + A (comutatividade)
A + (B + C) = (A + B) + C (associatividade)
A + 0 = A, em que 0 detona a matriz nula de ordem mxn
'''

'\nOperações matriciais - Exercício 2\nPara as matrizes a seguir,\n\n    | 10  11 |       | 1  25 |       | 7  3 |\nA = |  5  1  |   B = | 3   4 |   C = | 6  1 |\n    | -2  4  |       | 0 -10 |       | 0  0 |\n\nVerifique as propriedades da Adição de Matrizes:\n\nA + B = B + A (comutatividade)\nA + (B + C) = (A + B) + C (associatividade)\nA + 0 = A, em que 0 detona a matriz nula de ordem mxn\n'

In [15]:
A = np.array([[10, 11], [5, 1], [-2, 4]])
B = np.array([[1, 25], [3, 4], [0, -10]])
C = np.array([[7, 3], [6, 1], [0, 0]])
zero = np.zeros(shape=(3,2))

print(A+B==B+A)
print((A+(B+C))==((A+B)+C))
print(A+zero==A)


[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [16]:
'''
Operações matriciais - Exercício 3
Sejam as matrizes definidas a seguir, calculemos o que se pede na sequência.


    | 1  2  3 |       | -2  0  1 |       | -1 |      
A = | 2  1 -1 |   B = | 3   0  1 |   C = |  2 |  D = | 2 - 1 |
                                         |  4 |      

A+B
A.C (multiplicação de matrizes)
B.C
C.D
D.A
D.B
-A
-D
2A+3B
Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
'''

'\nOperações matriciais - Exercício 3\nSejam as matrizes definidas a seguir, calculemos o que se pede na sequência.\n\n\n    | 1  2  3 |       | -2  0  1 |       | -1 |      \nA = | 2  1 -1 |   B = | 3   0  1 |   C = |  2 |  D = | 2 - 1 |\n                                         |  4 |      \n\nA+B\nA.C (multiplicação de matrizes)\nB.C\nC.D\nD.A\nD.B\n-A\n-D\n2A+3B\nEste exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.\n'

In [17]:
A=np.array([[1,2,3],[2,1,-1]])
B=np.array([[-2,0,1],[3,0,1]])
C=np.array([[-1],[2],[4]])
D=np.array([[2,-1]])
#1
print('A+B:',A+B)
print()
#2
print('A.C',A.dot(C))
print()
#3
print('B.C',B.dot(C))
print()
#4
print('C.D',C.dot(D))
print()
#5
print('D.A',D.dot(A))
print()
#6
print('D.B',D.dot(B))
print()
#7
print('-A',(-1)*(A))
print()
#8
print('-D',(-1)*D)
print()
#9
print('2A+3B:',2*A+3*B)

A+B: [[-1  2  4]
 [ 5  1  0]]

A.C [[15]
 [-4]]

B.C [[6]
 [1]]

C.D [[-2  1]
 [ 4 -2]
 [ 8 -4]]

D.A [[0 3 7]]

D.B [[-7  0  1]]

-A [[-1 -2 -3]
 [-2 -1  1]]

-D [[-2  1]]

2A+3B: [[-4  4  9]
 [13  2  1]]


In [18]:
'''
Operações matriciais - Exercício 4
Sejam as matrizes A,B e C. Mostre que:
    AB = AC

    | 1  -3  2 |       | 1  4  1  0 |       | 2  1  -1  -2 |
A = | 2   1 -3 |   B = | 2  1  1  1 |   C = | 3 -2  -1  -1 |
    | 4  -3 -1 |       | 1 -2  1  2 |       | 2  -5  -1  0 |

'''

'\nOperações matriciais - Exercício 4\nSejam as matrizes A,B e C. Mostre que:\n    AB = AC\n\n    | 1  -3  2 |       | 1  4  1  0 |       | 2  1  -1  -2 |\nA = | 2   1 -3 |   B = | 2  1  1  1 |   C = | 3 -2  -1  -1 |\n    | 4  -3 -1 |       | 1 -2  1  2 |       | 2  -5  -1  0 |\n\n'

In [19]:
A = np.array([[1, -3, 2], [2, 1, -3], [4, -3, -1]])
B = np.array([[1, 4, 1, 0], [2, 1, 1, 1], [1, -2, 1, 2]])
C = np.array([[2, 1, -1, -2], [3, -1, -1, -1], [2, -5, -1, 0]])

print(A.dot(B)==A.dot(C))

[[ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]]


In [20]:
'''
Matriz Transposta - Exercício 1
Podemos obter a transposta de uma matriz permutando as linhas pelas colunas 
de mesmo índice(ou seja, o que é linha se transforma em coluna e o que é coluna se transforma em linha). 
Obtenha a Matriz transposta das matrizes a seguir:
    | 1  -3  2 |         | 1  0  4 |
A = | 2  1  -3 |     B = |-7  5  5 |  
    | 4  -3 -1 |         |25  9 11 |

Exemplo: Seja a matriz A definida a seguir, podemos obter sua transposta da seguinte forma:
    | 1  -2 |        | 1  7  20 |
A = | 4   4 |   AT = |-2  4  10 |
    |20  10 |        
'''

'\nMatriz Transposta - Exercício 1\nPodemos obter a transposta de uma matriz permutando as linhas pelas colunas \nde mesmo índice(ou seja, o que é linha se transforma em coluna e o que é coluna se transforma em linha). \nObtenha a Matriz transposta das matrizes a seguir:\n    | 1  -3  2 |         | 1  0  4 |\nA = | 2  1  -3 |     B = |-7  5  5 |  \n    | 4  -3 -1 |         |25  9 11 |\n\nExemplo: Seja a matriz A definida a seguir, podemos obter sua transposta da seguinte forma:\n    | 1  -2 |        | 1  7  20 |\nA = | 4   4 |   AT = |-2  4  10 |\n    |20  10 |        \n'

In [21]:
A = np.array([[1, -3, 2], [2, 1, -3], [4, -3, -1]])
B = np.array([[1, 0, 4], [-7, 5, 5], [25, 9, 11]])

print(A.T)
print()
print(B.T)


[[ 1  2  4]
 [-3  1 -3]
 [ 2 -3 -1]]

[[ 1 -7 25]
 [ 0  5  9]
 [ 4  5 11]]


In [22]:
'''
Determinante - Exercício 1
Obtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().
             | 1  2 |       | -3  -8 |       | 1  0 |
A = [5]  B = | 3  4 |   C = | -5  -2 |   D = | 0  1 |
'''                         

'\nDeterminante - Exercício 1\nObtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().\n             | 1  2 |       | -3  -8 |       | 1  0 |\nA = [5]  B = | 3  4 |   C = | -5  -2 |   D = | 0  1 |\n'

In [23]:
A = np.array([[5]])
B = np.array([[1, 2], [3, 4]])
C = np.array([[-3, -8], [-5, -2]])
D = np.array([[1, 0], [0, 1]])

print(np.linalg.det(A).round())
print()
print(np.linalg.det(B).round())
print()
print(np.linalg.det(C).round())
print()
print(np.linalg.det(D).round())

5.0

-2.0

-34.0

1.0


In [24]:
'''
Obtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().


    | 3  1  4 |         | 1  0  0 |        | 5  0  0 |       |3  0  0  0 |       | 5  0  13  12 |
A = |10  7  5 |     B = | 0  1  0 |    C = |10  0  0 |   D = |0  7  0  0 |   E = | 1  -1 25   7 |
    | 1  4  4 |         | 0  0  1 |        | 0  0  2 |       |0  0  11 0 |       | 6  2   1  20 |
                                                             |0  0  0  2 |       | 11 4   0  -9 |
'''                                                          

'\nObtenha o determinante das matrizes a seguir. Utilize o método np.linalg.det().\n\n\n    | 3  1  4 |         | 1  0  0 |        | 5  0  0 |       |3  0  0  0 |       | 5  0  13  12 |\nA = |10  7  5 |     B = | 0  1  0 |    C = |10  0  0 |   D = |0  7  0  0 |   E = | 1  -1 25   7 |\n    | 1  4  4 |         | 0  0  1 |        | 0  0  2 |       |0  0  11 0 |       | 6  2   1  20 |\n                                                             |0  0  0  2 |       | 11 4   0  -9 |\n'

In [25]:
A = np.array([[3, 1, 4], [ 10, 7, 5], [1, 4, 4]])
B = np.eye(3)
C = np.diag([5, 10, 2])
D  = np.diag([3, 7, 11, 2])
E = np.array([[5, 0, 13, 12], [ 1, -1, 25, 7], [6, 2, 1, 20], [11, 4, 0, -9]])

print(np.linalg.det(A).round())
print()
print(np.linalg.det(B).round())
print()
print(np.linalg.det(C).round())
print()
print(np.linalg.det(D).round())

121.0

1.0

100.0

462.0


In [26]:
'''
Determinante - Exercício 3
Dadas as matrizes A e B, calcule:

detA+detB

det(A+B)

    |1  2 |      | 3 -1 |
A = |1  0 |  B = | 0  1 |

Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
'''

'\nDeterminante - Exercício 3\nDadas as matrizes A e B, calcule:\n\ndetA+detB\n\ndet(A+B)\n\n    |1  2 |      | 3 -1 |\nA = |1  0 |  B = | 0  1 |\n\nEste exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.\n'

In [27]:
A = np.array([[1, 2], [1, 0]])
B = np.array([[3, -1], [0, 1]])

det_A = np.linalg.det(A).round()
det_B = np.linalg.det(B).round()
print(det_A+det_B)

1.0


In [28]:
'''
Matriz Inversa - Exercício 1
Encontre a inversa das matrizes abaixo. Use o método np.linalg.inv().

    |1  2 |      | -1  3 |
A = |3  4 |  B = |  5  4 |
'''

'\nMatriz Inversa - Exercício 1\nEncontre a inversa das matrizes abaixo. Use o método np.linalg.inv().\n\n    |1  2 |      | -1  3 |\nA = |3  4 |  B = |  5  4 |\n'

In [29]:
A = np.array([[1, 2], [3, 4]])
B= np.array([[-1, 3], [5, 4]])

A_inversa = np.linalg.inv(A)
B_inversa = np.linalg.inv(B) 

print(A_inversa)
print(B_inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.21052632  0.15789474]
 [ 0.26315789  0.05263158]]


In [30]:
'''
Matriz Inversa - Exercício 2
Encontre a inversa da matriz A:
    | 4  -1  2  -2 |
A = | 3  -1  0   0 |
    | 2   3  1   0 |
    | 0   7  1   1 |

Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
'''

'\nMatriz Inversa - Exercício 2\nEncontre a inversa da matriz A:\n    | 4  -1  2  -2 |\nA = | 3  -1  0   0 |\n    | 2   3  1   0 |\n    | 0   7  1   1 |\n\nEste exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.\n'

In [31]:
A = np.array([[4, -1, 2, -2], [3, -1, 0, 0 ], [2, 3, 1, 0], [0, 7, 1, 1]])
A_inverso = np.linalg.inv(A)
print(A_inverso)

[[ -1.  -1.   4.  -2.]
 [ -3.  -4.  12.  -6.]
 [ 11.  14. -43.  22.]
 [ 10.  14. -41.  21.]]


In [32]:
'''
Matriz Inversa - Exercício 3
Encontre a inversa da matriz A:

A = diagonal principal = 7, 8, 11, 2, 4, 5, 1, 3
'''

'\nMatriz Inversa - Exercício 3\nEncontre a inversa da matriz A:\n\nA = diagonal principal = 7, 8, 11, 2, 4, 5, 1, 3\n'

In [33]:
A = np.diag([7, 8, 11, 2, 4, 5, 1, 3])
A_inverso = np.linalg.inv(A)
print(A_inverso)

[[0.14285714 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.125      0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.09090909 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.25       0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.2
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333]]


In [33]:
'''
Sistemas Lineares - Exercício 1
Resolva os sistemas lineares a seguir. Utilize o método np.linalg.solve().

A = | 2x + 3x = 6   B= | 3x + y = 9 
    |  x -  y = 8      | x + 2y = 8
'''

In [34]:
#vetor A
A = np.array([[2, 3], [1, -1]])
B = np.array([[6], [8]])
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 6.]
 [-2.]]


In [35]:
#vetor B
A = np.array([[3,1], [1, 2]])
B = np.array([[9], [8]])
solucao = np.linalg.solve(A,B)
print(solucao)

[[2.]
 [3.]]


In [ ]:
'''
Sistemas Lineares - Exercício 2
Resolva o sistema linear abaixo.

|x + 3z = -8
|2x - 4 = -4
|3x - 2y - 5z = 26

Adaptação de : STEINBRUCH, A.; WINTERLE, P. Álgebra Linear. São Paulo: McGraw-Hill, 1987.


'''

In [40]:
A = np.array([[1, 0, 3], [2, -4, 0], [3, -2, -5]])
B = np.array([[-8], [-4],[26]])
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 4.]
 [ 3.]
 [-4.]]


In [ ]:
'''
Sistemas Lineares - Exercício 3
Resolva o sistema linear abaixo. Utilize o método np.linalg.solve().

|x + y + z + w = 0
|x + y + z - w = 4
|x + y - z + w = -4
|x - y + z + w = 2


Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
'''

In [42]:
A = np.array([[1, 1, 1, 1], [1, 1, 1, -1], [1, 1, -1, 1], [1, -1, 1, 1]])
B = np.array([[0], [4], [-4], [2]])
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 1.]
 [-1.]
 [ 2.]
 [-2.]]


In [ ]:
'''
Sistemas Lineares - Exercício 4
Resolva o sistema linear abaixo.

|3x + 2y = 2
|x - y = 4
|5y + z = -1
'''

In [48]:
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
B = np.array([[2], [4], [-1]])
solucao = np.linalg.solve(A,B)
print(solucao)

[[ 2.]
 [-2.]
 [ 9.]]


In [ ]:
'''
Traço de uma Matriz - Exercício 1
Obtenha o traço das matrizes abaixo:

    | 1  2 |         | 10  0  11 |        | 4   2  11  14 |
A = | 3  4 |     B = | -7  2   5 |    C = | 0  -9   1   3 |
                     | 45  78  4 |        |-3   4   5   8 |
                                          | 0   1   1   2 |

Lembrete: o traço de uma matriz é definido como a soma dos elementos da sua diagonal principal. Desta forma, 
facilmente podemos dizer que o traço da matriz A é 5, da matriz B 16 e da matriz C 2. Use o método matrix.trace().
'''

In [51]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 0, 11], [-7, 2, 5], [45, 78, 4]])
C = np.array([[4, 2, 11, 14], [0, -9, 1, 3], [-3, 4, 5, 8], [0, 1, 1, 2]])

print(np.trace(A))
print(np.trace(B))
print(np.trace(C))

5
16
2


In [ ]:
'''
Posto (rank) - Exercício 1
Obtenha o posto (ou rank) da matriz K. Use o método np.linalg.matrix_rank().

    | 2  -1  3 |
K = | 1   4  2 |
    | 1  -5  1 |
    | 4  16  8 |
Para mais informações: https://pt.wikipedia.org/wiki/Posto_matricial.

Este exercício é uma adaptção de BOLDRINI, J. et al. Álgebra Linear. São Paulo: Harbra, 1986.
'''

In [52]:
K = np.array([[2, -1, 3], [1, 4, 2], [1, -5, 1], [4, 16, 8]])
rank = np.linalg.matrix_rank(K)
print(rank)

2


In [ ]:
'''
Autovalor/Autovetor - Exercício 1
Calcule os autovalores associadoas a matriz A. Utilize o método np.linalg.eigvals().


A = | 1  3 |
    |-1  5 |

Adaptado de : STEINBRUCH, A.; WINTERLE, P. Álgebra Linear. São Paulo: McGraw-Hill, 1987.
'''

In [54]:
A = np.array([[1, 3], [-1, 5]])
solucao = np.linalg.eigvals(A)
print(solucao)

[2. 4.]
